name: CI
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
  - cron: 0 0 * * 0
permissions:
  contents: read
  actions: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with: { node-version: 24.x }
    - name: Install Packages
      run: npm ci --ignore-scripts
    - name: Lint
      run: npm run -s lint

  test:
    name: Test
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    permissions:
      checks: write

    strategy:
      matrix:
        eslint: [10.x]
        typescript-eslint: [8.x]
        node: [24.x]
        os: [ubuntu-latest]
        include:
        # On other platforms
        - eslint: 10.x
          typescript-eslint: 8.x
          node: 24.x
          os: windows-latest
        - eslint: 10.x
          typescript-eslint: 8.x
          node: 24.x
          os: macos-latest
        # On old Node.js versions
        - eslint: 10.x
          typescript-eslint: 8.x
          node: 18.x
          os: ubuntu-latest
        - eslint: 8.x
          typescript-eslint: 6.x
          node: 18.x
          os: ubuntu-latest
        # Other ESLint versions
        - eslint: 7.x
          typescript-eslint: 6.x
          node: 18.x
          os: ubuntu-latest
        - eslint: 8.x
          typescript-eslint: 6.x
          node: 20.x
          os: ubuntu-latest
        - eslint: 9.x
          typescript-eslint: 8.x
          node: 20.x
          os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with: { node-version: "${{ matrix.node }}" }
    - name: Install Packages
      run: npm install --ignore-scripts
    - name: Install ESLint ${{ matrix.eslint }} and TypeScript-ESLint ${{ matrix.typescript-eslint }}
      run: npm install --ignore-scripts --force --no-save eslint@${{ matrix.eslint }} @typescript-eslint/eslint-plugin@${{ matrix.typescript-eslint }}
    - name: Test
      run: npm run -s test:ci:${{ matrix.eslint }} -- --reporter json --reporter-options output=reports/tests.json
    - name: Test Report
      uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3
      if: success() || failure()
      with:
        name: Tests Results (${{ matrix.eslint }}, ${{ matrix.node }}, ${{ matrix.os }})
        path: reports/tests.json
        reporter: mocha-json
    - name: Send Coverage
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: "${{ secrets.CODECOV_TOKEN }}"
        directory: ./coverage/
