name: Publish
on:
  release:
    types: [released]

jobs:
  publish:
    name: Publish Package to npmjs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: "https://registry.npmjs.org"
        always-auth: true
    - name: Install Packages
      run: npm ci
    - name: Test
      run: |
        npm run -s test:ci
        npm run -s lint
    - name: Build
      run: |
        npm run -s build
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
